version: '3.9'

services:
  db:
    image: postgres:16
    container_name: hanabi_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: hanabi_dev
      POSTGRES_USER: hanabi_user
      POSTGRES_PASSWORD: hanabi_password
    ports:
      - '5432:5432'
    volumes:
      - hanabi_db_data:/var/lib/postgresql/data

volumes:
  hanabi_db_data:
